from django.urls import path, include
from .views import (add_bills_home,
                     balance_details,
                     transaction_edit,
                     delete_transaction,
                     group_create,
                     index_balances,
                     balance_list,
                     view_balance,
                     profile_view,
                     update_profile,
                     change_password,
                     group_list_view,
                     group_members_list_view,
                     remove_members,
                     add_members,
                     group_user_signup,
                     load_users,
                     group_list_bill,
                   )

urlpatterns =[
    path('accounts/update_profile',update_profile, name='update_profile'),
    path('accounts/profile',profile_view.as_view(), name='profile_view'),
    path('accounts/password', change_password, name='change_password'),
    path('addbills/<int:id>',add_bills_home, name='add_bills_home'),
    path('balance_list/<int:id>', balance_list, name='balance_list'),
    path('view_balance/<int:id>', view_balance, name='view_balance'),
    path('balance_details/<int:id>',balance_details, name='balance_details'),
    path('balance_details/transaction_edit/<int:id>',transaction_edit, name='transaction_edit'),
    path('transaction_delete/<int:id>',delete_transaction, name='transaction_delete'),
    path('group_create',group_create, name='group_create'),
    path('group_list/<int:id>',group_list_view, name='group_list'),
    path('group_list_bill/<int:id>',group_list_bill, name='group_list_bill'),
    path('group_members_list/<int:id>',group_members_list_view, name='group_members_list'),
    path('remove_members/<int:id>',remove_members, name='remove_members'),
    path('add_members/<int:id>',add_members, name='add_members'),
    path('member_signup/',group_user_signup, name='member_signup'),
    path('ajax/users_list/',load_users, name='ajax_load_users'),
    path('',index_balances, name='index'),
]
