# Generated by Django 3.0.1 on 2020-04-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_email', models.EmailField(max_length=254, verbose_name='Recipient Email')),
                ('group_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
