# Generated by Django 3.0.1 on 2020-04-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='group_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
