# Generated by Django 3.0.1 on 2020-05-12 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bills', '0004_auto_20200429_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='share_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.GroupMembers'),
        ),
    ]
