# Generated by Django 3.0.1 on 2020-05-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_auto_20200511_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='share_with',
        ),
    ]
