# Generated by Django 3.0.1 on 2020-05-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_remove_transactions_share_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='share_with',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
